# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taylor Rongaus
email: trongaus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Major at the University of Notre Dame
baseurl: "" # the subpath of your site, e.g. /blog
url: "trongaus.github.io" # the base hostname & protocol for your site
github_username:  trongaus

footer-links:
  email: trongaus@gmail.com
  github: trongaus
  linkedin: trongaus
  bitbucket: trongaus

# Build settings
markdown: kramdown
